server:
  ssh:
    port: 2222
    host_key: "certs/host_key"
    username: "admin"
    password: "changeme"  # Altere em produção!
  web:
    port: 8443
    cert_file: "certs/cert.pem"
    key_file: "certs/key.pem"

client:
  server_address: "localhost:2222"
  username: "admin"
  password: "changeme"  # Altere em produção!

persistence:
  enabled: true
  method: "registry"  # Windows: registry, Linux/macOS: service
  path: "/usr/local/bin/icsid"  # Caminho para o binário 